/* Generated by Yosys 0.5+ (git sha1 ba4cce9, gcc 4.8.4-2ubuntu1~14.04 -O2 -fstack-protector -fPIC -Os) */

(* src = "n_serial.v:1" *)
module n_serial(enable, parallel, serial, complete, reset, sd_clock, load_send);
  (* src = "n_serial.v:47" *)
  wire [31:0] _0000_;
  (* src = "n_serial.v:62" *)
  wire _0001_;
  (* src = "n_serial.v:28" *)
  wire [31:0] _0002_;
  (* src = "n_serial.v:28" *)
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire [31:0] _0647_;
  wire [31:0] _0648_;
  wire [31:0] _0649_;
  (* src = "n_serial.v:54" *)
  wire [31:0] _0650_;
  wire [15:0] _0651_;
  wire [7:0] _0652_;
  wire [3:0] _0653_;
  wire [1:0] _0654_;
  wire _0655_;
  wire [15:0] _0656_;
  wire [7:0] _0657_;
  wire [3:0] _0658_;
  wire [1:0] _0659_;
  wire _0660_;
  wire [31:0] _0661_;
  wire [31:0] _0662_;
  wire _0663_;
  (* src = "n_serial.v:64" *)
  wire _0664_;
  (* src = "n_serial.v:53" *)
  wire _0665_;
  wire [31:0] _0666_;
  wire [31:0] _0667_;
  wire _0668_;
  wire [31:0] _0669_;
  (* src = "n_serial.v:40|<techmap.v>:128" *)
  wire [31:0] _0670_;
  (* src = "n_serial.v:40|<techmap.v>:129" *)
  wire [31:0] _0671_;
  (* src = "n_serial.v:40|<techmap.v>:130" *)
  wire _0672_;
  wire [1023:0] _0673_;
  wire [1023:0] _0674_;
  (* src = "n_serial.v:40|<techmap.v>:142" *)
  wire [95:0] _0675_;
  (* src = "n_serial.v:40" *)
  wire _0676_;
  wire [31:0] _0677_;
  wire [31:0] _0678_;
  wire [31:0] _0679_;
  (* src = "n_serial.v:40" *)
  wire [31:0] _0680_;
  (* src = "<techmap.v>:246" *)
  wire [31:0] _0681_;
  (* src = "<techmap.v>:257" *)
  wire [31:0] _0682_;
  (* src = "<techmap.v>:253" *)
  wire [31:0] _0683_;
  (* src = "<techmap.v>:247" *)
  wire [31:0] _0684_;
  (* src = "<techmap.v>:258" *)
  wire [31:0] _0685_;
  (* src = "<techmap.v>:250" *)
  wire _0686_;
  (* src = "<techmap.v>:253" *)
  wire [31:0] _0687_;
  (* src = "<techmap.v>:250" *)
  wire _0688_;
  (* src = "<techmap.v>:251" *)
  wire [31:0] _0689_;
  (* src = "<techmap.v>:248" *)
  wire [31:0] _0690_;
  (* src = "<techmap.v>:248" *)
  wire [31:0] _0691_;
  (* src = "<techmap.v>:260|<techmap.v>:198" *)
  wire _0692_;
  (* src = "<techmap.v>:260|<techmap.v>:200" *)
  wire [31:0] _0693_;
  (* src = "<techmap.v>:260|<techmap.v>:197" *)
  wire [31:0] _0694_;
  (* src = "<techmap.v>:260|<techmap.v>:197" *)
  wire [31:0] _0695_;
  wire [1023:0] _0696_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _0697_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _0698_;
  wire [31:0] _0699_;
  wire [31:0] _0700_;
  (* src = "n_serial.v:40|<techmap.v>:145" *)
  wire [95:0] _0701_;
  (* src = "n_serial.v:40|<techmap.v>:145" *)
  wire [95:0] _0702_;
  (* src = "n_serial.v:40|<techmap.v>:145" *)
  wire [95:0] _0703_;
  (* src = "n_serial.v:40|<techmap.v>:145" *)
  wire [95:0] _0704_;
  (* src = "n_serial.v:40|<techmap.v>:145" *)
  wire [95:0] _0705_;
  (* src = "n_serial.v:40|<techmap.v>:145" *)
  wire [95:0] _0706_;
  (* src = "<techmap.v>:246" *)
  wire [31:0] _0707_;
  (* src = "<techmap.v>:257" *)
  wire [31:0] _0708_;
  (* src = "<techmap.v>:253" *)
  wire [31:0] _0709_;
  (* src = "<techmap.v>:247" *)
  wire [31:0] _0710_;
  (* src = "<techmap.v>:258" *)
  wire [31:0] _0711_;
  (* src = "<techmap.v>:250" *)
  wire _0712_;
  (* src = "<techmap.v>:253" *)
  wire [31:0] _0713_;
  (* src = "<techmap.v>:250" *)
  wire _0714_;
  (* src = "<techmap.v>:251" *)
  wire [31:0] _0715_;
  (* src = "<techmap.v>:248" *)
  wire [31:0] _0716_;
  (* src = "<techmap.v>:248" *)
  wire [31:0] _0717_;
  (* src = "<techmap.v>:260|<techmap.v>:198" *)
  wire _0718_;
  (* src = "<techmap.v>:260|<techmap.v>:200" *)
  wire [31:0] _0719_;
  (* src = "<techmap.v>:260|<techmap.v>:197" *)
  wire [31:0] _0720_;
  (* src = "<techmap.v>:260|<techmap.v>:197" *)
  wire [31:0] _0721_;
  wire [1023:0] _0722_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _0723_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _0724_;
  wire [31:0] _0725_;
  wire [31:0] _0726_;
  (* src = "<techmap.v>:260" *)
  wire [31:0] _0727_;
  (* src = "<techmap.v>:258" *)
  wire [31:0] _0728_;
  (* src = "<techmap.v>:258" *)
  wire [31:0] _0729_;
  (* src = "<techmap.v>:262" *)
  wire [31:0] _0730_;
  (* src = "<techmap.v>:263" *)
  wire [32:0] _0731_;
  (* src = "<techmap.v>:260|<techmap.v>:212" *)
  wire _0732_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0733_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0734_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0735_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0736_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0737_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0738_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0739_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0740_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0741_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0742_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0743_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0744_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0745_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0746_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0747_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0748_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0749_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0750_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0751_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0752_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0753_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0754_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0755_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0756_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0757_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0758_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0759_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0760_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0761_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0762_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0763_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0764_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0765_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0766_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0767_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0768_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0769_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0770_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0771_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0772_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0773_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0774_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0775_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0776_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0777_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0778_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0779_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0780_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0781_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0782_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0783_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0784_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0785_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0786_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0787_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0788_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0789_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0790_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0791_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0792_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0793_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0794_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0795_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0796_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0797_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0798_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0799_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0800_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0801_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0802_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0803_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0804_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0805_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0806_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0807_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0808_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0809_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0810_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0811_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0812_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0813_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0814_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0815_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0816_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0817_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0818_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0819_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0820_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0821_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0822_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0823_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0824_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0825_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0826_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0827_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0828_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0829_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0830_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0831_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0832_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0833_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0834_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0835_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0836_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0837_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0838_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0839_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0840_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0841_;
  (* src = "<techmap.v>:260" *)
  wire [31:0] _0842_;
  (* src = "<techmap.v>:258" *)
  wire [31:0] _0843_;
  (* src = "<techmap.v>:258" *)
  wire [31:0] _0844_;
  (* src = "<techmap.v>:262" *)
  wire [31:0] _0845_;
  (* src = "<techmap.v>:263" *)
  wire [32:0] _0846_;
  (* src = "<techmap.v>:260|<techmap.v>:212" *)
  wire _0847_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0848_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0849_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0850_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0851_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0852_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0853_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0854_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0855_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0856_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0857_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0858_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0859_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0860_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0861_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0862_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0863_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0864_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0865_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0866_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0867_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0868_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0869_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0870_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0871_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0872_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0873_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0874_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0875_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0876_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0877_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0878_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0879_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0880_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0881_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0882_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0883_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0884_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0885_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0886_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0887_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0888_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0889_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0890_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0891_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0892_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0893_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0894_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0895_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0896_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0897_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0898_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0899_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0900_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0901_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0902_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0903_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _0904_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0905_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0906_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0907_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0908_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0909_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0910_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0911_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0912_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0913_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0914_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0915_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0916_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0917_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0918_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0919_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0920_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0921_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0922_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0923_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0924_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0925_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0926_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0927_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0928_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0929_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _0930_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0931_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0932_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0933_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0934_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0935_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0936_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0937_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0938_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0939_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0940_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0941_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0942_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0943_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0944_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0945_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0946_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0947_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0948_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0949_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0950_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0951_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0952_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0953_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0954_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0955_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _0956_;
  (* src = "n_serial.v:11" *)
  output complete;
  reg complete;
  (* init = 32'd 0 *)
  (* src = "n_serial.v:23" *)
  reg [31:0] count;
  initial count = 32'd 0;
  (* src = "n_serial.v:4" *)
  input enable;
  (* src = "n_serial.v:5" *)
  input load_send;
  (* src = "n_serial.v:21" *)
  reg next_complete;
  (* src = "n_serial.v:6" *)
  input [31:0] parallel;
  (* init = 32'd 0 *)
  (* src = "n_serial.v:25" *)
  reg [31:0] parallel_cargado;
  initial parallel_cargado = 32'd 0;
  (* src = "n_serial.v:7" *)
  input reset;
  (* src = "n_serial.v:8" *)
  input sd_clock;
  (* src = "n_serial.v:10" *)
  output serial;
  reg serial;
  NOT _0957_ (
    .A(_0072_),
    .Y(_0142_)
  );
  NOT _0958_ (
    .A(_0073_),
    .Y(_0144_)
  );
  NOR _0959_ (
    .A(_0144_),
    .B(_0142_),
    .Y(_0145_)
  );
  NOT _0960_ (
    .A(_0007_),
    .Y(_0146_)
  );
  NOR _0961_ (
    .A(_0073_),
    .B(_0146_),
    .Y(_0147_)
  );
  NOR _0962_ (
    .A(_0147_),
    .B(_0145_),
    .Y(_0148_)
  );
  NOR _0963_ (
    .A(_0148_),
    .B(_0039_),
    .Y(_0040_)
  );
  NOR _0964_ (
    .A(_0073_),
    .B(_0008_),
    .Y(_0149_)
  );
  NOT _0965_ (
    .A(_0039_),
    .Y(_0150_)
  );
  NOT _0966_ (
    .A(_0074_),
    .Y(_0151_)
  );
  NAND _0967_ (
    .A(_0151_),
    .B(_0073_),
    .Y(_0152_)
  );
  NAND _0968_ (
    .A(_0152_),
    .B(_0150_),
    .Y(_0153_)
  );
  NOR _0969_ (
    .A(_0153_),
    .B(_0149_),
    .Y(_0041_)
  );
  NOR _0970_ (
    .A(_0073_),
    .B(_0009_),
    .Y(_0155_)
  );
  NOT _0971_ (
    .A(_0075_),
    .Y(_0156_)
  );
  NAND _0972_ (
    .A(_0156_),
    .B(_0073_),
    .Y(_0157_)
  );
  NAND _0973_ (
    .A(_0157_),
    .B(_0150_),
    .Y(_0158_)
  );
  NOR _0974_ (
    .A(_0158_),
    .B(_0155_),
    .Y(_0042_)
  );
  NOR _0975_ (
    .A(_0073_),
    .B(_0010_),
    .Y(_0159_)
  );
  NOT _0976_ (
    .A(_0076_),
    .Y(_0160_)
  );
  NAND _0977_ (
    .A(_0160_),
    .B(_0073_),
    .Y(_0161_)
  );
  NAND _0978_ (
    .A(_0161_),
    .B(_0150_),
    .Y(_0162_)
  );
  NOR _0979_ (
    .A(_0162_),
    .B(_0159_),
    .Y(_0043_)
  );
  NOT _0980_ (
    .A(_0077_),
    .Y(_0163_)
  );
  NOR _0981_ (
    .A(_0163_),
    .B(_0144_),
    .Y(_0164_)
  );
  NOT _0982_ (
    .A(_0011_),
    .Y(_0165_)
  );
  NOR _0983_ (
    .A(_0073_),
    .B(_0165_),
    .Y(_0166_)
  );
  NOR _0984_ (
    .A(_0166_),
    .B(_0164_),
    .Y(_0167_)
  );
  NOR _0985_ (
    .A(_0167_),
    .B(_0039_),
    .Y(_0044_)
  );
  NOT _0986_ (
    .A(_0078_),
    .Y(_0168_)
  );
  NOR _0987_ (
    .A(_0168_),
    .B(_0144_),
    .Y(_0169_)
  );
  NOT _0988_ (
    .A(_0012_),
    .Y(_0170_)
  );
  NOR _0989_ (
    .A(_0073_),
    .B(_0170_),
    .Y(_0171_)
  );
  NOR _0990_ (
    .A(_0171_),
    .B(_0169_),
    .Y(_0174_)
  );
  NOR _0991_ (
    .A(_0174_),
    .B(_0039_),
    .Y(_0045_)
  );
  NOT _0992_ (
    .A(_0079_),
    .Y(_0175_)
  );
  NOR _0993_ (
    .A(_0175_),
    .B(_0144_),
    .Y(_0176_)
  );
  NOT _0994_ (
    .A(_0013_),
    .Y(_0177_)
  );
  NOR _0995_ (
    .A(_0073_),
    .B(_0177_),
    .Y(_0178_)
  );
  NOR _0996_ (
    .A(_0178_),
    .B(_0176_),
    .Y(_0179_)
  );
  NOR _0997_ (
    .A(_0179_),
    .B(_0039_),
    .Y(_0046_)
  );
  NOT _0998_ (
    .A(_0080_),
    .Y(_0180_)
  );
  NOR _0999_ (
    .A(_0180_),
    .B(_0144_),
    .Y(_0181_)
  );
  NOT _1000_ (
    .A(_0014_),
    .Y(_0182_)
  );
  NOR _1001_ (
    .A(_0073_),
    .B(_0182_),
    .Y(_0183_)
  );
  NOR _1002_ (
    .A(_0183_),
    .B(_0181_),
    .Y(_0184_)
  );
  NOR _1003_ (
    .A(_0184_),
    .B(_0039_),
    .Y(_0047_)
  );
  NOR _1004_ (
    .A(_0073_),
    .B(_0015_),
    .Y(_0185_)
  );
  NOT _1005_ (
    .A(_0081_),
    .Y(_0186_)
  );
  NAND _1006_ (
    .A(_0186_),
    .B(_0073_),
    .Y(_0187_)
  );
  NAND _1007_ (
    .A(_0187_),
    .B(_0150_),
    .Y(_0188_)
  );
  NOR _1008_ (
    .A(_0188_),
    .B(_0185_),
    .Y(_0048_)
  );
  NOT _1009_ (
    .A(_0082_),
    .Y(_0189_)
  );
  NOR _1010_ (
    .A(_0189_),
    .B(_0144_),
    .Y(_0191_)
  );
  NOT _1011_ (
    .A(_0016_),
    .Y(_0192_)
  );
  NOR _1012_ (
    .A(_0073_),
    .B(_0192_),
    .Y(_0193_)
  );
  NOR _1013_ (
    .A(_0193_),
    .B(_0191_),
    .Y(_0194_)
  );
  NOR _1014_ (
    .A(_0194_),
    .B(_0039_),
    .Y(_0049_)
  );
  NOT _1015_ (
    .A(_0083_),
    .Y(_0195_)
  );
  NOR _1016_ (
    .A(_0195_),
    .B(_0144_),
    .Y(_0196_)
  );
  NOT _1017_ (
    .A(_0017_),
    .Y(_0197_)
  );
  NOR _1018_ (
    .A(_0073_),
    .B(_0197_),
    .Y(_0198_)
  );
  NOR _1019_ (
    .A(_0198_),
    .B(_0196_),
    .Y(_0199_)
  );
  NOR _1020_ (
    .A(_0199_),
    .B(_0039_),
    .Y(_0050_)
  );
  NOR _1021_ (
    .A(_0073_),
    .B(_0018_),
    .Y(_0200_)
  );
  NOT _1022_ (
    .A(_0084_),
    .Y(_0201_)
  );
  NAND _1023_ (
    .A(_0201_),
    .B(_0073_),
    .Y(_0202_)
  );
  NAND _1024_ (
    .A(_0202_),
    .B(_0150_),
    .Y(_0203_)
  );
  NOR _1025_ (
    .A(_0203_),
    .B(_0200_),
    .Y(_0051_)
  );
  NOR _1026_ (
    .A(_0073_),
    .B(_0019_),
    .Y(_0204_)
  );
  NOT _1027_ (
    .A(_0085_),
    .Y(_0205_)
  );
  NAND _1028_ (
    .A(_0205_),
    .B(_0073_),
    .Y(_0206_)
  );
  NAND _1029_ (
    .A(_0206_),
    .B(_0150_),
    .Y(_0207_)
  );
  NOR _1030_ (
    .A(_0207_),
    .B(_0204_),
    .Y(_0052_)
  );
  NOR _1031_ (
    .A(_0073_),
    .B(_0020_),
    .Y(_0209_)
  );
  NOT _1032_ (
    .A(_0086_),
    .Y(_0210_)
  );
  NAND _1033_ (
    .A(_0210_),
    .B(_0073_),
    .Y(_0211_)
  );
  NAND _1034_ (
    .A(_0211_),
    .B(_0150_),
    .Y(_0212_)
  );
  NOR _1035_ (
    .A(_0212_),
    .B(_0209_),
    .Y(_0053_)
  );
  NOR _1036_ (
    .A(_0073_),
    .B(_0021_),
    .Y(_0213_)
  );
  NOT _1037_ (
    .A(_0087_),
    .Y(_0214_)
  );
  NAND _1038_ (
    .A(_0214_),
    .B(_0073_),
    .Y(_0215_)
  );
  NAND _1039_ (
    .A(_0215_),
    .B(_0150_),
    .Y(_0216_)
  );
  NOR _1040_ (
    .A(_0216_),
    .B(_0213_),
    .Y(_0054_)
  );
  NOR _1041_ (
    .A(_0073_),
    .B(_0022_),
    .Y(_0217_)
  );
  NOT _1042_ (
    .A(_0088_),
    .Y(_0218_)
  );
  NAND _1043_ (
    .A(_0218_),
    .B(_0073_),
    .Y(_0219_)
  );
  NAND _1044_ (
    .A(_0219_),
    .B(_0150_),
    .Y(_0220_)
  );
  NOR _1045_ (
    .A(_0220_),
    .B(_0217_),
    .Y(_0055_)
  );
  NOT _1046_ (
    .A(_0089_),
    .Y(_0221_)
  );
  NOR _1047_ (
    .A(_0221_),
    .B(_0144_),
    .Y(_0222_)
  );
  NOT _1048_ (
    .A(_0023_),
    .Y(_0223_)
  );
  NOR _1049_ (
    .A(_0073_),
    .B(_0223_),
    .Y(_0224_)
  );
  NOR _1050_ (
    .A(_0224_),
    .B(_0222_),
    .Y(_0226_)
  );
  NOR _1051_ (
    .A(_0226_),
    .B(_0039_),
    .Y(_0056_)
  );
  NOR _1052_ (
    .A(_0073_),
    .B(_0024_),
    .Y(_0227_)
  );
  NOT _1053_ (
    .A(_0090_),
    .Y(_0228_)
  );
  NAND _1054_ (
    .A(_0228_),
    .B(_0073_),
    .Y(_0229_)
  );
  NAND _1055_ (
    .A(_0229_),
    .B(_0150_),
    .Y(_0230_)
  );
  NOR _1056_ (
    .A(_0230_),
    .B(_0227_),
    .Y(_0057_)
  );
  NOR _1057_ (
    .A(_0073_),
    .B(_0025_),
    .Y(_0231_)
  );
  NOT _1058_ (
    .A(_0091_),
    .Y(_0232_)
  );
  NAND _1059_ (
    .A(_0232_),
    .B(_0073_),
    .Y(_0233_)
  );
  NAND _1060_ (
    .A(_0233_),
    .B(_0150_),
    .Y(_0234_)
  );
  NOR _1061_ (
    .A(_0234_),
    .B(_0231_),
    .Y(_0058_)
  );
  NOT _1062_ (
    .A(_0092_),
    .Y(_0235_)
  );
  NOR _1063_ (
    .A(_0235_),
    .B(_0144_),
    .Y(_0236_)
  );
  NOT _1064_ (
    .A(_0026_),
    .Y(_0237_)
  );
  NOR _1065_ (
    .A(_0073_),
    .B(_0237_),
    .Y(_0238_)
  );
  NOR _1066_ (
    .A(_0238_),
    .B(_0236_),
    .Y(_0239_)
  );
  NOR _1067_ (
    .A(_0239_),
    .B(_0039_),
    .Y(_0059_)
  );
  NOT _1068_ (
    .A(_0093_),
    .Y(_0240_)
  );
  NOR _1069_ (
    .A(_0240_),
    .B(_0144_),
    .Y(_0241_)
  );
  NOT _1070_ (
    .A(_0027_),
    .Y(_0243_)
  );
  NOR _1071_ (
    .A(_0073_),
    .B(_0243_),
    .Y(_0244_)
  );
  NOR _1072_ (
    .A(_0244_),
    .B(_0241_),
    .Y(_0245_)
  );
  NOR _1073_ (
    .A(_0245_),
    .B(_0039_),
    .Y(_0060_)
  );
  NOT _1074_ (
    .A(_0094_),
    .Y(_0246_)
  );
  NOR _1075_ (
    .A(_0246_),
    .B(_0144_),
    .Y(_0247_)
  );
  NOT _1076_ (
    .A(_0028_),
    .Y(_0248_)
  );
  NOR _1077_ (
    .A(_0073_),
    .B(_0248_),
    .Y(_0249_)
  );
  NOR _1078_ (
    .A(_0249_),
    .B(_0247_),
    .Y(_0250_)
  );
  NOR _1079_ (
    .A(_0250_),
    .B(_0039_),
    .Y(_0061_)
  );
  NOT _1080_ (
    .A(_0095_),
    .Y(_0251_)
  );
  NOR _1081_ (
    .A(_0251_),
    .B(_0144_),
    .Y(_0252_)
  );
  NOT _1082_ (
    .A(_0029_),
    .Y(_0253_)
  );
  NOR _1083_ (
    .A(_0073_),
    .B(_0253_),
    .Y(_0254_)
  );
  NOR _1084_ (
    .A(_0254_),
    .B(_0252_),
    .Y(_0255_)
  );
  NOR _1085_ (
    .A(_0255_),
    .B(_0039_),
    .Y(_0062_)
  );
  NOR _1086_ (
    .A(_0073_),
    .B(_0030_),
    .Y(_0256_)
  );
  NOT _1087_ (
    .A(_0096_),
    .Y(_0257_)
  );
  NAND _1088_ (
    .A(_0257_),
    .B(_0073_),
    .Y(_0258_)
  );
  NAND _1089_ (
    .A(_0258_),
    .B(_0150_),
    .Y(_0259_)
  );
  NOR _1090_ (
    .A(_0259_),
    .B(_0256_),
    .Y(_0063_)
  );
  NOR _1091_ (
    .A(_0073_),
    .B(_0031_),
    .Y(_0261_)
  );
  NOT _1092_ (
    .A(_0097_),
    .Y(_0262_)
  );
  NAND _1093_ (
    .A(_0262_),
    .B(_0073_),
    .Y(_0263_)
  );
  NAND _1094_ (
    .A(_0263_),
    .B(_0150_),
    .Y(_0264_)
  );
  NOR _1095_ (
    .A(_0264_),
    .B(_0261_),
    .Y(_0064_)
  );
  NOT _1096_ (
    .A(_0098_),
    .Y(_0265_)
  );
  NOR _1097_ (
    .A(_0265_),
    .B(_0144_),
    .Y(_0266_)
  );
  NOT _1098_ (
    .A(_0032_),
    .Y(_0267_)
  );
  NOR _1099_ (
    .A(_0073_),
    .B(_0267_),
    .Y(_0268_)
  );
  NOR _1100_ (
    .A(_0268_),
    .B(_0266_),
    .Y(_0269_)
  );
  NOR _1101_ (
    .A(_0269_),
    .B(_0039_),
    .Y(_0065_)
  );
  NOT _1102_ (
    .A(_0099_),
    .Y(_0270_)
  );
  NOR _1103_ (
    .A(_0270_),
    .B(_0144_),
    .Y(_0271_)
  );
  NOT _1104_ (
    .A(_0033_),
    .Y(_0272_)
  );
  NOR _1105_ (
    .A(_0073_),
    .B(_0272_),
    .Y(_0273_)
  );
  NOR _1106_ (
    .A(_0273_),
    .B(_0271_),
    .Y(_0274_)
  );
  NOR _1107_ (
    .A(_0274_),
    .B(_0039_),
    .Y(_0066_)
  );
  NOT _1108_ (
    .A(_0100_),
    .Y(_0275_)
  );
  NOR _1109_ (
    .A(_0275_),
    .B(_0144_),
    .Y(_0276_)
  );
  NOT _1110_ (
    .A(_0034_),
    .Y(_0278_)
  );
  NOR _1111_ (
    .A(_0073_),
    .B(_0278_),
    .Y(_0279_)
  );
  NOR _1112_ (
    .A(_0279_),
    .B(_0276_),
    .Y(_0280_)
  );
  NOR _1113_ (
    .A(_0280_),
    .B(_0039_),
    .Y(_0068_)
  );
  NOR _1114_ (
    .A(_0073_),
    .B(_0035_),
    .Y(_0281_)
  );
  NOT _1115_ (
    .A(_0101_),
    .Y(_0282_)
  );
  NAND _1116_ (
    .A(_0282_),
    .B(_0073_),
    .Y(_0283_)
  );
  NAND _1117_ (
    .A(_0283_),
    .B(_0150_),
    .Y(_0284_)
  );
  NOR _1118_ (
    .A(_0284_),
    .B(_0281_),
    .Y(_0069_)
  );
  NOR _1119_ (
    .A(_0073_),
    .B(_0036_),
    .Y(_0285_)
  );
  NOT _1120_ (
    .A(_0102_),
    .Y(_0286_)
  );
  NAND _1121_ (
    .A(_0286_),
    .B(_0073_),
    .Y(_0287_)
  );
  NAND _1122_ (
    .A(_0287_),
    .B(_0150_),
    .Y(_0288_)
  );
  NOR _1123_ (
    .A(_0288_),
    .B(_0285_),
    .Y(_0070_)
  );
  NOR _1124_ (
    .A(_0073_),
    .B(_0037_),
    .Y(_0289_)
  );
  NOT _1125_ (
    .A(_0103_),
    .Y(_0290_)
  );
  NAND _1126_ (
    .A(_0290_),
    .B(_0073_),
    .Y(_0291_)
  );
  NAND _1127_ (
    .A(_0291_),
    .B(_0150_),
    .Y(_0292_)
  );
  NOR _1128_ (
    .A(_0292_),
    .B(_0289_),
    .Y(_0071_)
  );
  NOT _1129_ (
    .A(_0225_),
    .Y(_0293_)
  );
  NOT _1130_ (
    .A(_0260_),
    .Y(_0295_)
  );
  NOT _1131_ (
    .A(_0277_),
    .Y(_0296_)
  );
  NOR _1132_ (
    .A(_0296_),
    .B(_0295_),
    .Y(_0297_)
  );
  NAND _1133_ (
    .A(_0297_),
    .B(_0242_),
    .Y(_0298_)
  );
  NOR _1134_ (
    .A(_0298_),
    .B(_0293_),
    .Y(_0299_)
  );
  NAND _1135_ (
    .A(_0646_),
    .B(_0536_),
    .Y(_0300_)
  );
  NOT _1136_ (
    .A(_0300_),
    .Y(_0301_)
  );
  NAND _1137_ (
    .A(_0301_),
    .B(_0356_),
    .Y(_0302_)
  );
  NOT _1138_ (
    .A(_0302_),
    .Y(_0303_)
  );
  NAND _1139_ (
    .A(_0303_),
    .B(_0172_),
    .Y(_0304_)
  );
  NAND _1140_ (
    .A(_0357_),
    .B(_0336_),
    .Y(_0305_)
  );
  NAND _1141_ (
    .A(_0315_),
    .B(_0294_),
    .Y(_0306_)
  );
  NOR _1142_ (
    .A(_0306_),
    .B(_0305_),
    .Y(_0307_)
  );
  NOT _1143_ (
    .A(_0307_),
    .Y(_0308_)
  );
  NOT _1144_ (
    .A(_0004_),
    .Y(_0309_)
  );
  NOT _1145_ (
    .A(_0556_),
    .Y(_0310_)
  );
  NOR _1146_ (
    .A(_0310_),
    .B(_0309_),
    .Y(_0311_)
  );
  NOT _1147_ (
    .A(_0378_),
    .Y(_0312_)
  );
  NOT _1148_ (
    .A(_0396_),
    .Y(_0313_)
  );
  NOR _1149_ (
    .A(_0313_),
    .B(_0312_),
    .Y(_0314_)
  );
  NAND _1150_ (
    .A(_0314_),
    .B(_0311_),
    .Y(_0316_)
  );
  NOR _1151_ (
    .A(_0316_),
    .B(_0308_),
    .Y(_0317_)
  );
  NOT _1152_ (
    .A(_0317_),
    .Y(_0318_)
  );
  NOR _1153_ (
    .A(_0318_),
    .B(_0304_),
    .Y(_0319_)
  );
  NAND _1154_ (
    .A(_0319_),
    .B(_0299_),
    .Y(_0320_)
  );
  NAND _1155_ (
    .A(_0208_),
    .B(_0190_),
    .Y(_0321_)
  );
  NOT _1156_ (
    .A(_0321_),
    .Y(_0322_)
  );
  NOT _1157_ (
    .A(_0154_),
    .Y(_0323_)
  );
  NOT _1158_ (
    .A(_0173_),
    .Y(_0324_)
  );
  NOR _1159_ (
    .A(_0324_),
    .B(_0323_),
    .Y(_0325_)
  );
  NAND _1160_ (
    .A(_0325_),
    .B(_0322_),
    .Y(_0326_)
  );
  NOT _1161_ (
    .A(_0006_),
    .Y(_0327_)
  );
  NAND _1162_ (
    .A(_0136_),
    .B(_0067_),
    .Y(_0328_)
  );
  NOR _1163_ (
    .A(_0328_),
    .B(_0327_),
    .Y(_0329_)
  );
  NAND _1164_ (
    .A(_0329_),
    .B(_0005_),
    .Y(_0330_)
  );
  NOR _1165_ (
    .A(_0330_),
    .B(_0326_),
    .Y(_0331_)
  );
  NOT _1166_ (
    .A(_0135_),
    .Y(_0332_)
  );
  NAND _1167_ (
    .A(_0501_),
    .B(_0481_),
    .Y(_0333_)
  );
  NAND _1168_ (
    .A(_0465_),
    .B(_0448_),
    .Y(_0334_)
  );
  NOR _1169_ (
    .A(_0334_),
    .B(_0333_),
    .Y(_0335_)
  );
  NOT _1170_ (
    .A(_0414_),
    .Y(_0337_)
  );
  NOT _1171_ (
    .A(_0431_),
    .Y(_0338_)
  );
  NOR _1172_ (
    .A(_0338_),
    .B(_0337_),
    .Y(_0339_)
  );
  NAND _1173_ (
    .A(_0339_),
    .B(_0335_),
    .Y(_0340_)
  );
  NOR _1174_ (
    .A(_0340_),
    .B(_0332_),
    .Y(_0341_)
  );
  NAND _1175_ (
    .A(_0341_),
    .B(_0331_),
    .Y(_0342_)
  );
  NOR _1176_ (
    .A(_0342_),
    .B(_0320_),
    .Y(_0343_)
  );
  NAND _1177_ (
    .A(_0343_),
    .B(_0521_),
    .Y(_0344_)
  );
  NOT _1178_ (
    .A(_0344_),
    .Y(_0345_)
  );
  NOT _1179_ (
    .A(_0521_),
    .Y(_0346_)
  );
  NOT _1180_ (
    .A(_0343_),
    .Y(_0347_)
  );
  NAND _1181_ (
    .A(_0347_),
    .B(_0346_),
    .Y(_0348_)
  );
  NAND _1182_ (
    .A(_0348_),
    .B(_0150_),
    .Y(_0349_)
  );
  NOR _1183_ (
    .A(_0349_),
    .B(_0345_),
    .Y(_0104_)
  );
  NOR _1184_ (
    .A(_0135_),
    .B(_0310_),
    .Y(_0350_)
  );
  NOR _1185_ (
    .A(_0340_),
    .B(_0313_),
    .Y(_0351_)
  );
  NAND _1186_ (
    .A(_0351_),
    .B(_0378_),
    .Y(_0352_)
  );
  NAND _1187_ (
    .A(_0307_),
    .B(_0299_),
    .Y(_0353_)
  );
  NOR _1188_ (
    .A(_0353_),
    .B(_0352_),
    .Y(_0354_)
  );
  NAND _1189_ (
    .A(_0354_),
    .B(_0331_),
    .Y(_0355_)
  );
  NOR _1190_ (
    .A(_0355_),
    .B(_0304_),
    .Y(_0358_)
  );
  NAND _1191_ (
    .A(_0358_),
    .B(_0004_),
    .Y(_0359_)
  );
  NOR _1192_ (
    .A(_0359_),
    .B(_0556_),
    .Y(_0360_)
  );
  NOT _1193_ (
    .A(_0304_),
    .Y(_0361_)
  );
  NOT _1194_ (
    .A(_0331_),
    .Y(_0362_)
  );
  NOT _1195_ (
    .A(_0335_),
    .Y(_0363_)
  );
  NAND _1196_ (
    .A(_0339_),
    .B(_0314_),
    .Y(_0364_)
  );
  NOR _1197_ (
    .A(_0364_),
    .B(_0363_),
    .Y(_0365_)
  );
  NOT _1198_ (
    .A(_0242_),
    .Y(_0366_)
  );
  NAND _1199_ (
    .A(_0277_),
    .B(_0260_),
    .Y(_0367_)
  );
  NOR _1200_ (
    .A(_0367_),
    .B(_0366_),
    .Y(_0368_)
  );
  NAND _1201_ (
    .A(_0368_),
    .B(_0225_),
    .Y(_0369_)
  );
  NOR _1202_ (
    .A(_0308_),
    .B(_0369_),
    .Y(_0370_)
  );
  NAND _1203_ (
    .A(_0370_),
    .B(_0365_),
    .Y(_0371_)
  );
  NOR _1204_ (
    .A(_0371_),
    .B(_0362_),
    .Y(_0372_)
  );
  NAND _1205_ (
    .A(_0372_),
    .B(_0361_),
    .Y(_0373_)
  );
  NOR _1206_ (
    .A(_0373_),
    .B(_0309_),
    .Y(_0374_)
  );
  NOR _1207_ (
    .A(_0374_),
    .B(_0310_),
    .Y(_0375_)
  );
  NOR _1208_ (
    .A(_0375_),
    .B(_0360_),
    .Y(_0376_)
  );
  NOR _1209_ (
    .A(_0376_),
    .B(_0332_),
    .Y(_0377_)
  );
  NOR _1210_ (
    .A(_0377_),
    .B(_0350_),
    .Y(_0379_)
  );
  NOR _1211_ (
    .A(_0379_),
    .B(_0039_),
    .Y(_0105_)
  );
  NOT _1212_ (
    .A(_0306_),
    .Y(_0380_)
  );
  NAND _1213_ (
    .A(_0341_),
    .B(_0314_),
    .Y(_0381_)
  );
  NOR _1214_ (
    .A(_0381_),
    .B(_0305_),
    .Y(_0382_)
  );
  NAND _1215_ (
    .A(_0382_),
    .B(_0380_),
    .Y(_0383_)
  );
  NOR _1216_ (
    .A(_0383_),
    .B(_0369_),
    .Y(_0384_)
  );
  NAND _1217_ (
    .A(_0384_),
    .B(_0331_),
    .Y(_0385_)
  );
  NOR _1218_ (
    .A(_0385_),
    .B(_0304_),
    .Y(_0386_)
  );
  NOR _1219_ (
    .A(_0386_),
    .B(_0004_),
    .Y(_0387_)
  );
  NAND _1220_ (
    .A(_0386_),
    .B(_0004_),
    .Y(_0388_)
  );
  NAND _1221_ (
    .A(_0388_),
    .B(_0150_),
    .Y(_0389_)
  );
  NOR _1222_ (
    .A(_0389_),
    .B(_0387_),
    .Y(_0106_)
  );
  NOR _1223_ (
    .A(_0385_),
    .B(_0302_),
    .Y(_0390_)
  );
  NOR _1224_ (
    .A(_0390_),
    .B(_0172_),
    .Y(_0391_)
  );
  NOT _1225_ (
    .A(_0386_),
    .Y(_0392_)
  );
  NAND _1226_ (
    .A(_0392_),
    .B(_0150_),
    .Y(_0393_)
  );
  NOR _1227_ (
    .A(_0393_),
    .B(_0391_),
    .Y(_0107_)
  );
  NOR _1228_ (
    .A(_0385_),
    .B(_0300_),
    .Y(_0394_)
  );
  NOR _1229_ (
    .A(_0394_),
    .B(_0356_),
    .Y(_0395_)
  );
  NOT _1230_ (
    .A(_0390_),
    .Y(_0397_)
  );
  NAND _1231_ (
    .A(_0397_),
    .B(_0150_),
    .Y(_0398_)
  );
  NOR _1232_ (
    .A(_0398_),
    .B(_0395_),
    .Y(_0108_)
  );
  NOT _1233_ (
    .A(_0646_),
    .Y(_0399_)
  );
  NOR _1234_ (
    .A(_0385_),
    .B(_0399_),
    .Y(_0400_)
  );
  NOR _1235_ (
    .A(_0400_),
    .B(_0536_),
    .Y(_0401_)
  );
  NOT _1236_ (
    .A(_0394_),
    .Y(_0402_)
  );
  NAND _1237_ (
    .A(_0402_),
    .B(_0150_),
    .Y(_0403_)
  );
  NOR _1238_ (
    .A(_0403_),
    .B(_0401_),
    .Y(_0109_)
  );
  NOT _1239_ (
    .A(_0385_),
    .Y(_0404_)
  );
  NOR _1240_ (
    .A(_0404_),
    .B(_0646_),
    .Y(_0405_)
  );
  NOT _1241_ (
    .A(_0400_),
    .Y(_0406_)
  );
  NAND _1242_ (
    .A(_0406_),
    .B(_0150_),
    .Y(_0407_)
  );
  NOR _1243_ (
    .A(_0407_),
    .B(_0405_),
    .Y(_0110_)
  );
  NOT _1244_ (
    .A(_0329_),
    .Y(_0408_)
  );
  NOT _1245_ (
    .A(_0326_),
    .Y(_0409_)
  );
  NAND _1246_ (
    .A(_0384_),
    .B(_0409_),
    .Y(_0410_)
  );
  NOR _1247_ (
    .A(_0410_),
    .B(_0408_),
    .Y(_0411_)
  );
  NOR _1248_ (
    .A(_0411_),
    .B(_0005_),
    .Y(_0412_)
  );
  NOT _1249_ (
    .A(_0330_),
    .Y(_0413_)
  );
  NOT _1250_ (
    .A(_0410_),
    .Y(_0415_)
  );
  NAND _1251_ (
    .A(_0415_),
    .B(_0413_),
    .Y(_0416_)
  );
  NAND _1252_ (
    .A(_0416_),
    .B(_0150_),
    .Y(_0417_)
  );
  NOR _1253_ (
    .A(_0417_),
    .B(_0412_),
    .Y(_0111_)
  );
  NOR _1254_ (
    .A(_0410_),
    .B(_0328_),
    .Y(_0418_)
  );
  NOR _1255_ (
    .A(_0418_),
    .B(_0006_),
    .Y(_0419_)
  );
  NOT _1256_ (
    .A(_0411_),
    .Y(_0420_)
  );
  NAND _1257_ (
    .A(_0420_),
    .B(_0150_),
    .Y(_0421_)
  );
  NOR _1258_ (
    .A(_0421_),
    .B(_0419_),
    .Y(_0112_)
  );
  NOT _1259_ (
    .A(_0136_),
    .Y(_0422_)
  );
  NOR _1260_ (
    .A(_0410_),
    .B(_0422_),
    .Y(_0423_)
  );
  NOR _1261_ (
    .A(_0423_),
    .B(_0067_),
    .Y(_0424_)
  );
  NOT _1262_ (
    .A(_0418_),
    .Y(_0425_)
  );
  NAND _1263_ (
    .A(_0425_),
    .B(_0150_),
    .Y(_0426_)
  );
  NOR _1264_ (
    .A(_0426_),
    .B(_0424_),
    .Y(_0113_)
  );
  NAND _1265_ (
    .A(_0410_),
    .B(_0422_),
    .Y(_0427_)
  );
  NAND _1266_ (
    .A(_0427_),
    .B(_0150_),
    .Y(_0428_)
  );
  NOR _1267_ (
    .A(_0428_),
    .B(_0423_),
    .Y(_0114_)
  );
  NAND _1268_ (
    .A(_0384_),
    .B(_0322_),
    .Y(_0429_)
  );
  NOR _1269_ (
    .A(_0429_),
    .B(_0324_),
    .Y(_0430_)
  );
  NAND _1270_ (
    .A(_0430_),
    .B(_0154_),
    .Y(_0432_)
  );
  NOT _1271_ (
    .A(_0190_),
    .Y(_0433_)
  );
  NAND _1272_ (
    .A(_0384_),
    .B(_0208_),
    .Y(_0434_)
  );
  NOR _1273_ (
    .A(_0434_),
    .B(_0433_),
    .Y(_0435_)
  );
  NAND _1274_ (
    .A(_0435_),
    .B(_0173_),
    .Y(_0436_)
  );
  NAND _1275_ (
    .A(_0436_),
    .B(_0323_),
    .Y(_0437_)
  );
  NAND _1276_ (
    .A(_0437_),
    .B(_0432_),
    .Y(_0438_)
  );
  NOR _1277_ (
    .A(_0438_),
    .B(_0039_),
    .Y(_0115_)
  );
  NAND _1278_ (
    .A(_0429_),
    .B(_0324_),
    .Y(_0439_)
  );
  NAND _1279_ (
    .A(_0439_),
    .B(_0150_),
    .Y(_0440_)
  );
  NOR _1280_ (
    .A(_0440_),
    .B(_0430_),
    .Y(_0116_)
  );
  NAND _1281_ (
    .A(_0434_),
    .B(_0433_),
    .Y(_0441_)
  );
  NAND _1282_ (
    .A(_0441_),
    .B(_0429_),
    .Y(_0442_)
  );
  NOR _1283_ (
    .A(_0442_),
    .B(_0039_),
    .Y(_0117_)
  );
  NOR _1284_ (
    .A(_0384_),
    .B(_0208_),
    .Y(_0443_)
  );
  NAND _1285_ (
    .A(_0434_),
    .B(_0150_),
    .Y(_0444_)
  );
  NOR _1286_ (
    .A(_0444_),
    .B(_0443_),
    .Y(_0118_)
  );
  NOR _1287_ (
    .A(_0383_),
    .B(_0298_),
    .Y(_0445_)
  );
  NOR _1288_ (
    .A(_0445_),
    .B(_0225_),
    .Y(_0446_)
  );
  NOT _1289_ (
    .A(_0384_),
    .Y(_0447_)
  );
  NAND _1290_ (
    .A(_0447_),
    .B(_0150_),
    .Y(_0449_)
  );
  NOR _1291_ (
    .A(_0449_),
    .B(_0446_),
    .Y(_0119_)
  );
  NOR _1292_ (
    .A(_0383_),
    .B(_0367_),
    .Y(_0450_)
  );
  NOR _1293_ (
    .A(_0450_),
    .B(_0242_),
    .Y(_0451_)
  );
  NOT _1294_ (
    .A(_0445_),
    .Y(_0452_)
  );
  NAND _1295_ (
    .A(_0452_),
    .B(_0150_),
    .Y(_0453_)
  );
  NOR _1296_ (
    .A(_0453_),
    .B(_0451_),
    .Y(_0120_)
  );
  NOR _1297_ (
    .A(_0383_),
    .B(_0296_),
    .Y(_0454_)
  );
  NOR _1298_ (
    .A(_0454_),
    .B(_0260_),
    .Y(_0455_)
  );
  NOT _1299_ (
    .A(_0450_),
    .Y(_0456_)
  );
  NAND _1300_ (
    .A(_0456_),
    .B(_0150_),
    .Y(_0457_)
  );
  NOR _1301_ (
    .A(_0457_),
    .B(_0455_),
    .Y(_0121_)
  );
  NOT _1302_ (
    .A(_0454_),
    .Y(_0458_)
  );
  NAND _1303_ (
    .A(_0383_),
    .B(_0296_),
    .Y(_0459_)
  );
  NAND _1304_ (
    .A(_0459_),
    .B(_0458_),
    .Y(_0460_)
  );
  NOR _1305_ (
    .A(_0460_),
    .B(_0039_),
    .Y(_0122_)
  );
  NAND _1306_ (
    .A(_0382_),
    .B(_0315_),
    .Y(_0461_)
  );
  NOT _1307_ (
    .A(_0461_),
    .Y(_0462_)
  );
  NOR _1308_ (
    .A(_0462_),
    .B(_0294_),
    .Y(_0463_)
  );
  NAND _1309_ (
    .A(_0383_),
    .B(_0150_),
    .Y(_0464_)
  );
  NOR _1310_ (
    .A(_0464_),
    .B(_0463_),
    .Y(_0123_)
  );
  NOR _1311_ (
    .A(_0382_),
    .B(_0315_),
    .Y(_0466_)
  );
  NAND _1312_ (
    .A(_0461_),
    .B(_0150_),
    .Y(_0467_)
  );
  NOR _1313_ (
    .A(_0467_),
    .B(_0466_),
    .Y(_0124_)
  );
  NOT _1314_ (
    .A(_0357_),
    .Y(_0468_)
  );
  NOR _1315_ (
    .A(_0381_),
    .B(_0468_),
    .Y(_0469_)
  );
  NOR _1316_ (
    .A(_0469_),
    .B(_0336_),
    .Y(_0470_)
  );
  NOT _1317_ (
    .A(_0382_),
    .Y(_0471_)
  );
  NAND _1318_ (
    .A(_0471_),
    .B(_0150_),
    .Y(_0472_)
  );
  NOR _1319_ (
    .A(_0472_),
    .B(_0470_),
    .Y(_0125_)
  );
  NOT _1320_ (
    .A(_0469_),
    .Y(_0473_)
  );
  NAND _1321_ (
    .A(_0381_),
    .B(_0468_),
    .Y(_0474_)
  );
  NAND _1322_ (
    .A(_0474_),
    .B(_0473_),
    .Y(_0475_)
  );
  NOR _1323_ (
    .A(_0475_),
    .B(_0039_),
    .Y(_0126_)
  );
  NAND _1324_ (
    .A(_0341_),
    .B(_0396_),
    .Y(_0476_)
  );
  NAND _1325_ (
    .A(_0476_),
    .B(_0312_),
    .Y(_0477_)
  );
  NAND _1326_ (
    .A(_0477_),
    .B(_0381_),
    .Y(_0478_)
  );
  NOR _1327_ (
    .A(_0478_),
    .B(_0039_),
    .Y(_0127_)
  );
  NOR _1328_ (
    .A(_0341_),
    .B(_0396_),
    .Y(_0479_)
  );
  NAND _1329_ (
    .A(_0476_),
    .B(_0150_),
    .Y(_0480_)
  );
  NOR _1330_ (
    .A(_0480_),
    .B(_0479_),
    .Y(_0128_)
  );
  NOR _1331_ (
    .A(_0363_),
    .B(_0332_),
    .Y(_0482_)
  );
  NAND _1332_ (
    .A(_0482_),
    .B(_0431_),
    .Y(_0483_)
  );
  NAND _1333_ (
    .A(_0483_),
    .B(_0337_),
    .Y(_0484_)
  );
  NOR _1334_ (
    .A(_0341_),
    .B(_0039_),
    .Y(_0485_)
  );
  NAND _1335_ (
    .A(_0485_),
    .B(_0484_),
    .Y(_0486_)
  );
  NOT _1336_ (
    .A(_0570_),
    .Y(_0487_)
  );
  NOR _1337_ (
    .A(_0556_),
    .B(_0521_),
    .Y(_0488_)
  );
  NAND _1338_ (
    .A(_0488_),
    .B(_0487_),
    .Y(_0489_)
  );
  NOR _1339_ (
    .A(_0357_),
    .B(_0336_),
    .Y(_0490_)
  );
  NOR _1340_ (
    .A(_0378_),
    .B(_0315_),
    .Y(_0491_)
  );
  NAND _1341_ (
    .A(_0491_),
    .B(_0490_),
    .Y(_0492_)
  );
  NOR _1342_ (
    .A(_0260_),
    .B(_0242_),
    .Y(_0493_)
  );
  NOR _1343_ (
    .A(_0294_),
    .B(_0277_),
    .Y(_0494_)
  );
  NAND _1344_ (
    .A(_0494_),
    .B(_0493_),
    .Y(_0495_)
  );
  NOR _1345_ (
    .A(_0495_),
    .B(_0492_),
    .Y(_0496_)
  );
  NOT _1346_ (
    .A(_0496_),
    .Y(_0497_)
  );
  NOR _1347_ (
    .A(_0497_),
    .B(_0489_),
    .Y(_0498_)
  );
  NAND _1348_ (
    .A(_0335_),
    .B(_0431_),
    .Y(_0499_)
  );
  NOR _1349_ (
    .A(_0536_),
    .B(_0356_),
    .Y(_0500_)
  );
  NOR _1350_ (
    .A(_0005_),
    .B(_0646_),
    .Y(_0502_)
  );
  NAND _1351_ (
    .A(_0502_),
    .B(_0500_),
    .Y(_0503_)
  );
  NOR _1352_ (
    .A(_0172_),
    .B(_0004_),
    .Y(_0504_)
  );
  NOR _1353_ (
    .A(_0414_),
    .B(_0396_),
    .Y(_0505_)
  );
  NAND _1354_ (
    .A(_0505_),
    .B(_0504_),
    .Y(_0506_)
  );
  NOR _1355_ (
    .A(_0506_),
    .B(_0503_),
    .Y(_0507_)
  );
  NOR _1356_ (
    .A(_0208_),
    .B(_0190_),
    .Y(_0508_)
  );
  NOR _1357_ (
    .A(_0225_),
    .B(_0173_),
    .Y(_0509_)
  );
  NAND _1358_ (
    .A(_0509_),
    .B(_0508_),
    .Y(_0510_)
  );
  NOR _1359_ (
    .A(_0067_),
    .B(_0006_),
    .Y(_0511_)
  );
  NOR _1360_ (
    .A(_0154_),
    .B(_0136_),
    .Y(_0512_)
  );
  NAND _1361_ (
    .A(_0512_),
    .B(_0511_),
    .Y(_0513_)
  );
  NOR _1362_ (
    .A(_0513_),
    .B(_0510_),
    .Y(_0514_)
  );
  NAND _1363_ (
    .A(_0514_),
    .B(_0507_),
    .Y(_0515_)
  );
  NOR _1364_ (
    .A(_0515_),
    .B(_0499_),
    .Y(_0516_)
  );
  NAND _1365_ (
    .A(_0516_),
    .B(_0498_),
    .Y(_0517_)
  );
  NOR _1366_ (
    .A(_0517_),
    .B(_0332_),
    .Y(_0518_)
  );
  NOR _1367_ (
    .A(_0518_),
    .B(_0486_),
    .Y(_0129_)
  );
  NOR _1368_ (
    .A(_0482_),
    .B(_0431_),
    .Y(_0519_)
  );
  NAND _1369_ (
    .A(_0483_),
    .B(_0150_),
    .Y(_0520_)
  );
  NOR _1370_ (
    .A(_0520_),
    .B(_0519_),
    .Y(_0130_)
  );
  NOT _1371_ (
    .A(_0482_),
    .Y(_0522_)
  );
  NOT _1372_ (
    .A(_0448_),
    .Y(_0523_)
  );
  NOR _1373_ (
    .A(_0333_),
    .B(_0332_),
    .Y(_0524_)
  );
  NAND _1374_ (
    .A(_0524_),
    .B(_0465_),
    .Y(_0525_)
  );
  NAND _1375_ (
    .A(_0525_),
    .B(_0523_),
    .Y(_0526_)
  );
  NAND _1376_ (
    .A(_0526_),
    .B(_0522_),
    .Y(_0527_)
  );
  NOR _1377_ (
    .A(_0527_),
    .B(_0039_),
    .Y(_0131_)
  );
  NOR _1378_ (
    .A(_0524_),
    .B(_0465_),
    .Y(_0528_)
  );
  NAND _1379_ (
    .A(_0525_),
    .B(_0150_),
    .Y(_0529_)
  );
  NOR _1380_ (
    .A(_0529_),
    .B(_0528_),
    .Y(_0132_)
  );
  NOT _1381_ (
    .A(_0481_),
    .Y(_0530_)
  );
  NAND _1382_ (
    .A(_0135_),
    .B(_0501_),
    .Y(_0531_)
  );
  NAND _1383_ (
    .A(_0531_),
    .B(_0530_),
    .Y(_0532_)
  );
  NAND _1384_ (
    .A(_0532_),
    .B(_0150_),
    .Y(_0533_)
  );
  NOR _1385_ (
    .A(_0533_),
    .B(_0524_),
    .Y(_0133_)
  );
  NOR _1386_ (
    .A(_0135_),
    .B(_0501_),
    .Y(_0534_)
  );
  NAND _1387_ (
    .A(_0531_),
    .B(_0150_),
    .Y(_0535_)
  );
  NOR _1388_ (
    .A(_0535_),
    .B(_0534_),
    .Y(_0134_)
  );
  NOT _1389_ (
    .A(_0517_),
    .Y(_0137_)
  );
  NOR _1390_ (
    .A(_0345_),
    .B(_0487_),
    .Y(_0537_)
  );
  NOR _1391_ (
    .A(_0344_),
    .B(_0570_),
    .Y(_0538_)
  );
  NOR _1392_ (
    .A(_0538_),
    .B(_0537_),
    .Y(_0539_)
  );
  NOR _1393_ (
    .A(_0539_),
    .B(_0039_),
    .Y(_0138_)
  );
  NOR _1394_ (
    .A(_0008_),
    .B(_0431_),
    .Y(_0540_)
  );
  NOR _1395_ (
    .A(_0024_),
    .B(_0338_),
    .Y(_0541_)
  );
  NOR _1396_ (
    .A(_0541_),
    .B(_0540_),
    .Y(_0542_)
  );
  NOR _1397_ (
    .A(_0542_),
    .B(_0448_),
    .Y(_0543_)
  );
  NAND _1398_ (
    .A(_0267_),
    .B(_0431_),
    .Y(_0544_)
  );
  NAND _1399_ (
    .A(_0192_),
    .B(_0338_),
    .Y(_0545_)
  );
  NAND _1400_ (
    .A(_0545_),
    .B(_0544_),
    .Y(_0546_)
  );
  NAND _1401_ (
    .A(_0546_),
    .B(_0448_),
    .Y(_0547_)
  );
  NAND _1402_ (
    .A(_0547_),
    .B(_0481_),
    .Y(_0548_)
  );
  NOR _1403_ (
    .A(_0548_),
    .B(_0543_),
    .Y(_0549_)
  );
  NOT _1404_ (
    .A(_0501_),
    .Y(_0550_)
  );
  NAND _1405_ (
    .A(_0030_),
    .B(_0431_),
    .Y(_0551_)
  );
  NOR _1406_ (
    .A(_0182_),
    .B(_0431_),
    .Y(_0552_)
  );
  NOR _1407_ (
    .A(_0552_),
    .B(_0523_),
    .Y(_0553_)
  );
  NAND _1408_ (
    .A(_0553_),
    .B(_0551_),
    .Y(_0554_)
  );
  NOT _1409_ (
    .A(_0038_),
    .Y(_0555_)
  );
  NOR _1410_ (
    .A(_0555_),
    .B(_0431_),
    .Y(_0557_)
  );
  NAND _1411_ (
    .A(_0022_),
    .B(_0431_),
    .Y(_0558_)
  );
  NAND _1412_ (
    .A(_0558_),
    .B(_0523_),
    .Y(_0559_)
  );
  NOR _1413_ (
    .A(_0559_),
    .B(_0557_),
    .Y(_0560_)
  );
  NOR _1414_ (
    .A(_0560_),
    .B(_0481_),
    .Y(_0561_)
  );
  NAND _1415_ (
    .A(_0561_),
    .B(_0554_),
    .Y(_0562_)
  );
  NAND _1416_ (
    .A(_0562_),
    .B(_0550_),
    .Y(_0563_)
  );
  NOR _1417_ (
    .A(_0563_),
    .B(_0549_),
    .Y(_0564_)
  );
  NOR _1418_ (
    .A(_0009_),
    .B(_0431_),
    .Y(_0565_)
  );
  NOR _1419_ (
    .A(_0025_),
    .B(_0338_),
    .Y(_0566_)
  );
  NOR _1420_ (
    .A(_0566_),
    .B(_0565_),
    .Y(_0567_)
  );
  NOR _1421_ (
    .A(_0567_),
    .B(_0448_),
    .Y(_0568_)
  );
  NAND _1422_ (
    .A(_0272_),
    .B(_0431_),
    .Y(_0569_)
  );
  NAND _1423_ (
    .A(_0197_),
    .B(_0338_),
    .Y(_0571_)
  );
  NAND _1424_ (
    .A(_0571_),
    .B(_0569_),
    .Y(_0572_)
  );
  NAND _1425_ (
    .A(_0572_),
    .B(_0448_),
    .Y(_0573_)
  );
  NAND _1426_ (
    .A(_0573_),
    .B(_0481_),
    .Y(_0574_)
  );
  NOR _1427_ (
    .A(_0574_),
    .B(_0568_),
    .Y(_0575_)
  );
  NAND _1428_ (
    .A(_0146_),
    .B(_0338_),
    .Y(_0576_)
  );
  NAND _1429_ (
    .A(_0223_),
    .B(_0431_),
    .Y(_0577_)
  );
  NAND _1430_ (
    .A(_0577_),
    .B(_0576_),
    .Y(_0578_)
  );
  NAND _1431_ (
    .A(_0578_),
    .B(_0523_),
    .Y(_0579_)
  );
  NOR _1432_ (
    .A(_0031_),
    .B(_0338_),
    .Y(_0580_)
  );
  NOR _1433_ (
    .A(_0015_),
    .B(_0431_),
    .Y(_0581_)
  );
  NOR _1434_ (
    .A(_0581_),
    .B(_0580_),
    .Y(_0582_)
  );
  NOR _1435_ (
    .A(_0582_),
    .B(_0523_),
    .Y(_0583_)
  );
  NOR _1436_ (
    .A(_0583_),
    .B(_0481_),
    .Y(_0584_)
  );
  NAND _1437_ (
    .A(_0584_),
    .B(_0579_),
    .Y(_0585_)
  );
  NAND _1438_ (
    .A(_0585_),
    .B(_0501_),
    .Y(_0586_)
  );
  NOR _1439_ (
    .A(_0586_),
    .B(_0575_),
    .Y(_0587_)
  );
  NOR _1440_ (
    .A(_0587_),
    .B(_0564_),
    .Y(_0588_)
  );
  NOR _1441_ (
    .A(_0588_),
    .B(_0465_),
    .Y(_0589_)
  );
  NAND _1442_ (
    .A(_0170_),
    .B(_0338_),
    .Y(_0590_)
  );
  NAND _1443_ (
    .A(_0248_),
    .B(_0431_),
    .Y(_0591_)
  );
  NAND _1444_ (
    .A(_0591_),
    .B(_0590_),
    .Y(_0592_)
  );
  NAND _1445_ (
    .A(_0592_),
    .B(_0523_),
    .Y(_0593_)
  );
  NOR _1446_ (
    .A(_0036_),
    .B(_0338_),
    .Y(_0594_)
  );
  NOR _1447_ (
    .A(_0020_),
    .B(_0431_),
    .Y(_0595_)
  );
  NOR _1448_ (
    .A(_0595_),
    .B(_0594_),
    .Y(_0596_)
  );
  NOR _1449_ (
    .A(_0596_),
    .B(_0523_),
    .Y(_0597_)
  );
  NOR _1450_ (
    .A(_0597_),
    .B(_0530_),
    .Y(_0598_)
  );
  NAND _1451_ (
    .A(_0598_),
    .B(_0593_),
    .Y(_0599_)
  );
  NOR _1452_ (
    .A(_0278_),
    .B(_0338_),
    .Y(_0600_)
  );
  NAND _1453_ (
    .A(_0018_),
    .B(_0338_),
    .Y(_0601_)
  );
  NAND _1454_ (
    .A(_0601_),
    .B(_0448_),
    .Y(_0602_)
  );
  NOR _1455_ (
    .A(_0602_),
    .B(_0600_),
    .Y(_0603_)
  );
  NAND _1456_ (
    .A(_0010_),
    .B(_0338_),
    .Y(_0604_)
  );
  NOR _1457_ (
    .A(_0237_),
    .B(_0338_),
    .Y(_0605_)
  );
  NOR _1458_ (
    .A(_0605_),
    .B(_0448_),
    .Y(_0606_)
  );
  NAND _1459_ (
    .A(_0606_),
    .B(_0604_),
    .Y(_0607_)
  );
  NAND _1460_ (
    .A(_0607_),
    .B(_0530_),
    .Y(_0608_)
  );
  NOR _1461_ (
    .A(_0608_),
    .B(_0603_),
    .Y(_0609_)
  );
  NOR _1462_ (
    .A(_0609_),
    .B(_0501_),
    .Y(_0610_)
  );
  NAND _1463_ (
    .A(_0610_),
    .B(_0599_),
    .Y(_0611_)
  );
  NAND _1464_ (
    .A(_0177_),
    .B(_0338_),
    .Y(_0612_)
  );
  NAND _1465_ (
    .A(_0253_),
    .B(_0431_),
    .Y(_0613_)
  );
  NAND _1466_ (
    .A(_0613_),
    .B(_0612_),
    .Y(_0614_)
  );
  NAND _1467_ (
    .A(_0614_),
    .B(_0523_),
    .Y(_0615_)
  );
  NOR _1468_ (
    .A(_0037_),
    .B(_0338_),
    .Y(_0616_)
  );
  NOR _1469_ (
    .A(_0021_),
    .B(_0431_),
    .Y(_0617_)
  );
  NOR _1470_ (
    .A(_0617_),
    .B(_0616_),
    .Y(_0618_)
  );
  NOR _1471_ (
    .A(_0618_),
    .B(_0523_),
    .Y(_0619_)
  );
  NOR _1472_ (
    .A(_0619_),
    .B(_0530_),
    .Y(_0620_)
  );
  NAND _1473_ (
    .A(_0620_),
    .B(_0615_),
    .Y(_0621_)
  );
  NOR _1474_ (
    .A(_0035_),
    .B(_0338_),
    .Y(_0622_)
  );
  NOR _1475_ (
    .A(_0019_),
    .B(_0431_),
    .Y(_0623_)
  );
  NOR _1476_ (
    .A(_0623_),
    .B(_0622_),
    .Y(_0624_)
  );
  NOR _1477_ (
    .A(_0624_),
    .B(_0523_),
    .Y(_0625_)
  );
  NAND _1478_ (
    .A(_0165_),
    .B(_0338_),
    .Y(_0626_)
  );
  NAND _1479_ (
    .A(_0243_),
    .B(_0431_),
    .Y(_0627_)
  );
  NAND _1480_ (
    .A(_0627_),
    .B(_0626_),
    .Y(_0628_)
  );
  NAND _1481_ (
    .A(_0628_),
    .B(_0523_),
    .Y(_0629_)
  );
  NAND _1482_ (
    .A(_0629_),
    .B(_0530_),
    .Y(_0630_)
  );
  NOR _1483_ (
    .A(_0630_),
    .B(_0625_),
    .Y(_0631_)
  );
  NOR _1484_ (
    .A(_0631_),
    .B(_0550_),
    .Y(_0632_)
  );
  NAND _1485_ (
    .A(_0632_),
    .B(_0621_),
    .Y(_0633_)
  );
  NAND _1486_ (
    .A(_0633_),
    .B(_0611_),
    .Y(_0634_)
  );
  NAND _1487_ (
    .A(_0634_),
    .B(_0465_),
    .Y(_0635_)
  );
  NAND _1488_ (
    .A(_0635_),
    .B(_0505_),
    .Y(_0636_)
  );
  NOR _1489_ (
    .A(_0636_),
    .B(_0589_),
    .Y(_0637_)
  );
  NOR _1490_ (
    .A(_0637_),
    .B(_0332_),
    .Y(_0638_)
  );
  NOT _1491_ (
    .A(_0139_),
    .Y(_0639_)
  );
  NAND _1492_ (
    .A(_0639_),
    .B(_0332_),
    .Y(_0640_)
  );
  NAND _1493_ (
    .A(_0640_),
    .B(_0150_),
    .Y(_0641_)
  );
  NOR _1494_ (
    .A(_0641_),
    .B(_0638_),
    .Y(_0140_)
  );
  NOT _1495_ (
    .A(_0141_),
    .Y(_0642_)
  );
  NOR _1496_ (
    .A(_0642_),
    .B(_0144_),
    .Y(_0643_)
  );
  NOR _1497_ (
    .A(_0073_),
    .B(_0555_),
    .Y(_0644_)
  );
  NOR _1498_ (
    .A(_0644_),
    .B(_0643_),
    .Y(_0645_)
  );
  NOR _1499_ (
    .A(_0645_),
    .B(_0039_),
    .Y(_0143_)
  );
  (* src = "n_serial.v:71" *)
  always @(negedge sd_clock)
      complete <= next_complete;
  (* src = "n_serial.v:62" *)
  always @(posedge sd_clock)
      next_complete <= _0001_;
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[0] <= _0000_[0];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[1] <= _0000_[1];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[2] <= _0000_[2];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[3] <= _0000_[3];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[4] <= _0000_[4];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[5] <= _0000_[5];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[6] <= _0000_[6];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[7] <= _0000_[7];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[8] <= _0000_[8];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[9] <= _0000_[9];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[10] <= _0000_[10];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[11] <= _0000_[11];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[12] <= _0000_[12];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[13] <= _0000_[13];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[14] <= _0000_[14];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[15] <= _0000_[15];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[16] <= _0000_[16];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[17] <= _0000_[17];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[18] <= _0000_[18];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[19] <= _0000_[19];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[20] <= _0000_[20];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[21] <= _0000_[21];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[22] <= _0000_[22];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[23] <= _0000_[23];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[24] <= _0000_[24];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[25] <= _0000_[25];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[26] <= _0000_[26];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[27] <= _0000_[27];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[28] <= _0000_[28];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[29] <= _0000_[29];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[30] <= _0000_[30];
  (* src = "n_serial.v:47" *)
  always @(negedge sd_clock)
      count[31] <= _0000_[31];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      serial <= _0003_;
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[0] <= _0002_[0];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[1] <= _0002_[1];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[2] <= _0002_[2];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[3] <= _0002_[3];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[4] <= _0002_[4];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[5] <= _0002_[5];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[6] <= _0002_[6];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[7] <= _0002_[7];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[8] <= _0002_[8];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[9] <= _0002_[9];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[10] <= _0002_[10];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[11] <= _0002_[11];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[12] <= _0002_[12];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[13] <= _0002_[13];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[14] <= _0002_[14];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[15] <= _0002_[15];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[16] <= _0002_[16];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[17] <= _0002_[17];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[18] <= _0002_[18];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[19] <= _0002_[19];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[20] <= _0002_[20];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[21] <= _0002_[21];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[22] <= _0002_[22];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[23] <= _0002_[23];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[24] <= _0002_[24];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[25] <= _0002_[25];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[26] <= _0002_[26];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[27] <= _0002_[27];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[28] <= _0002_[28];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[29] <= _0002_[29];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[30] <= _0002_[30];
  (* src = "n_serial.v:28" *)
  always @(posedge sd_clock)
      parallel_cargado[31] <= _0002_[31];
  assign _0674_ = 1024'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100001101001111010011100101001101010100010011010100000101010000001110110010000001101111011100000111010001011111011011010111010101111000011101000111001001100101011001010011101100100000011011110111000001110100010111110110001101101111011011100111001101110100001000000010110101101101011101010111100001011111011101010110111001100100011001010110011000100000001011010110110101110101011110000101111101100010011011110110111101101100001000000010110101100110011010010110111001100101001110110011101100111011;
  assign _0676_ = _0675_[0];
  assign _0673_ = 1024'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011100000111001001101111011000110011101100111011;
  assign _0708_ = _0709_;
  assign _0711_ = _0844_;
  assign _0725_ = _0845_;
  assign _0680_ = _0846_[31:0];
  assign _0682_ = _0683_;
  assign _0685_ = _0729_;
  assign _0699_ = _0730_;
  assign _0650_ = _0731_[31:0];
  assign _0722_ = 1024'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011100000111001001101111011000110011101100100000011011110111000001110100001000000010110101100110011000010111001101110100;
  assign _0723_ = _0726_;
  assign _0724_[0] = _0725_[0];
  assign _0713_ = count;
  assign _0709_ = 32'd 31;
  assign _0696_ = 1024'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011100000111001001101111011000110011101100100000011011110111000001110100001000000010110101100110011000010111001101110100;
  assign _0697_ = _0700_;
  assign _0698_[0] = _0699_[0];
  assign _0687_ = count;
  assign _0683_ = 32'd 1;
  assign _0004_ = count[28];
  assign _0172_ = count[27];
  assign _0356_ = count[26];
  assign _0536_ = count[25];
  assign _0646_ = count[24];
  assign _0005_ = count[23];
  assign _0006_ = count[22];
  assign _0067_ = count[21];
  assign _0136_ = count[20];
  assign _0154_ = count[19];
  assign _0173_ = count[18];
  assign _0190_ = count[17];
  assign _0208_ = count[16];
  assign _0225_ = count[15];
  assign _0242_ = count[14];
  assign _0260_ = count[13];
  assign _0277_ = count[12];
  assign _0294_ = count[11];
  assign _0315_ = count[10];
  assign _0336_ = count[9];
  assign _0357_ = count[8];
  assign _0378_ = count[7];
  assign _0396_ = count[6];
  assign _0414_ = count[5];
  assign _0431_ = count[4];
  assign _0448_ = count[3];
  assign _0465_ = count[2];
  assign _0481_ = count[1];
  assign _0501_ = count[0];
  assign _0521_ = count[30];
  assign _0556_ = count[29];
  assign _0570_ = count[31];
  assign _0007_ = parallel_cargado[30];
  assign _0008_ = parallel_cargado[29];
  assign _0009_ = parallel_cargado[28];
  assign _0010_ = parallel_cargado[27];
  assign _0011_ = parallel_cargado[26];
  assign _0012_ = parallel_cargado[25];
  assign _0013_ = parallel_cargado[24];
  assign _0014_ = parallel_cargado[23];
  assign _0015_ = parallel_cargado[22];
  assign _0016_ = parallel_cargado[21];
  assign _0017_ = parallel_cargado[20];
  assign _0018_ = parallel_cargado[19];
  assign _0019_ = parallel_cargado[18];
  assign _0020_ = parallel_cargado[17];
  assign _0021_ = parallel_cargado[16];
  assign _0022_ = parallel_cargado[15];
  assign _0023_ = parallel_cargado[14];
  assign _0024_ = parallel_cargado[13];
  assign _0025_ = parallel_cargado[12];
  assign _0026_ = parallel_cargado[11];
  assign _0027_ = parallel_cargado[10];
  assign _0028_ = parallel_cargado[9];
  assign _0029_ = parallel_cargado[8];
  assign _0030_ = parallel_cargado[7];
  assign _0031_ = parallel_cargado[6];
  assign _0032_ = parallel_cargado[5];
  assign _0033_ = parallel_cargado[4];
  assign _0034_ = parallel_cargado[3];
  assign _0035_ = parallel_cargado[2];
  assign _0036_ = parallel_cargado[1];
  assign _0037_ = parallel_cargado[0];
  assign _0038_ = parallel_cargado[31];
  assign _0039_ = reset;
  assign _0002_[30] = _0040_;
  assign _0002_[29] = _0041_;
  assign _0002_[28] = _0042_;
  assign _0002_[27] = _0043_;
  assign _0002_[26] = _0044_;
  assign _0002_[25] = _0045_;
  assign _0002_[24] = _0046_;
  assign _0002_[23] = _0047_;
  assign _0002_[22] = _0048_;
  assign _0002_[21] = _0049_;
  assign _0002_[20] = _0050_;
  assign _0002_[19] = _0051_;
  assign _0002_[18] = _0052_;
  assign _0002_[17] = _0053_;
  assign _0002_[16] = _0054_;
  assign _0002_[15] = _0055_;
  assign _0002_[14] = _0056_;
  assign _0002_[13] = _0057_;
  assign _0002_[12] = _0058_;
  assign _0002_[11] = _0059_;
  assign _0002_[10] = _0060_;
  assign _0002_[9] = _0061_;
  assign _0002_[8] = _0062_;
  assign _0002_[7] = _0063_;
  assign _0002_[6] = _0064_;
  assign _0002_[5] = _0065_;
  assign _0002_[4] = _0066_;
  assign _0002_[3] = _0068_;
  assign _0002_[2] = _0069_;
  assign _0002_[1] = _0070_;
  assign _0002_[0] = _0071_;
  assign _0072_ = parallel[30];
  assign _0073_ = enable;
  assign _0074_ = parallel[29];
  assign _0075_ = parallel[28];
  assign _0076_ = parallel[27];
  assign _0077_ = parallel[26];
  assign _0078_ = parallel[25];
  assign _0079_ = parallel[24];
  assign _0080_ = parallel[23];
  assign _0081_ = parallel[22];
  assign _0082_ = parallel[21];
  assign _0083_ = parallel[20];
  assign _0084_ = parallel[19];
  assign _0085_ = parallel[18];
  assign _0086_ = parallel[17];
  assign _0087_ = parallel[16];
  assign _0088_ = parallel[15];
  assign _0089_ = parallel[14];
  assign _0090_ = parallel[13];
  assign _0091_ = parallel[12];
  assign _0092_ = parallel[11];
  assign _0093_ = parallel[10];
  assign _0094_ = parallel[9];
  assign _0095_ = parallel[8];
  assign _0096_ = parallel[7];
  assign _0097_ = parallel[6];
  assign _0098_ = parallel[5];
  assign _0099_ = parallel[4];
  assign _0100_ = parallel[3];
  assign _0101_ = parallel[2];
  assign _0102_ = parallel[1];
  assign _0103_ = parallel[0];
  assign _0000_[30] = _0104_;
  assign _0000_[29] = _0105_;
  assign _0000_[28] = _0106_;
  assign _0000_[27] = _0107_;
  assign _0000_[26] = _0108_;
  assign _0000_[25] = _0109_;
  assign _0000_[24] = _0110_;
  assign _0000_[23] = _0111_;
  assign _0000_[22] = _0112_;
  assign _0000_[21] = _0113_;
  assign _0000_[20] = _0114_;
  assign _0000_[19] = _0115_;
  assign _0000_[18] = _0116_;
  assign _0000_[17] = _0117_;
  assign _0000_[16] = _0118_;
  assign _0000_[15] = _0119_;
  assign _0000_[14] = _0120_;
  assign _0000_[13] = _0121_;
  assign _0000_[12] = _0122_;
  assign _0000_[11] = _0123_;
  assign _0000_[10] = _0124_;
  assign _0000_[9] = _0125_;
  assign _0000_[8] = _0126_;
  assign _0000_[7] = _0127_;
  assign _0000_[6] = _0128_;
  assign _0000_[5] = _0129_;
  assign _0000_[4] = _0130_;
  assign _0000_[3] = _0131_;
  assign _0000_[2] = _0132_;
  assign _0000_[1] = _0133_;
  assign _0000_[0] = _0134_;
  assign _0135_ = load_send;
  assign _0001_ = _0137_;
  assign _0000_[31] = _0138_;
  assign _0139_ = serial;
  assign _0003_ = _0140_;
  assign _0141_ = parallel[31];
  assign _0002_[31] = _0143_;
endmodule
